version: '2.3'

services:
    api:
        image: gdeon/sanic:develop
        build: .
        image: gdeon/sanic:develop
        restart: unless-stopped
        ports:
            - 8000:8000
        environment:
            SERVER_IP: 0.0.0.0
            SERVER_PORT: 8000
            PG_CONNECTION: postgresql://admin:admin@31.184.215.77:5432/point_db
    flask_api:
        image: gdeon/flask_parse:develop
        restart: unless-stopped
        ports:
            - 5000:5000
        environment:
            REDIS_CONN: redis://redis:6379/1

volumes:
    flask_api:
=======
            PG_CONNECTION:
>>>>>>> c0c47e19ebc135a6751550541874a394e14b1e4a
