version: '2.3'

services:
    api:
        build: .
        restart: unless-stopped
        depends_on:
            - redis
        ports: 
            - 8000:8000
        environment:
            REDIS_CONNECTION: redis://redis:6379/1
            SERVER_IP: 0.0.0.0
            SERVER_PORT: 8000
    redis:
        image: redis:alpine
        restart: unless-stopped
        volumes:
            - ./storage/redis/data:/data
        ports:
            - 6389:6379
volumes:
    redis: