version: '2.3'

services:
    api:
        build: .
        image: gdeon/sanic:develop
        restart: unless-stopped
        ports:
            - 8000:8000
        environment:
            SERVER_IP: 0.0.0.0
            SERVER_PORT: 8000
            PG_CONNECTION:
