"""empty message

Revision ID: 2e08f61a0480
Revises: 98c2ee6e7b47
Create Date: 2020-05-01 19:24:32.963893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e08f61a0480'
down_revision = '98c2ee6e7b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='ID пользователя'),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order_users', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.add_column('order_users', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('order_users', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_users', 'file_type')
    op.drop_column('order_users', 'file_name')
    op.drop_column('order_users', 'file_data')
    op.drop_table('files')
    # ### end Alembic commands ###
