"""empty message

Revision ID: 546b234e241b
Revises: a8c0559bccef
Create Date: 2020-04-15 20:46:56.359245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546b234e241b'
down_revision = 'a8c0559bccef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_users', sa.Column('google_disk_link', sa.String(), nullable=True))
    op.add_column('points', sa.Column('google_disk_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'google_disk_link')
    op.drop_column('order_users', 'google_disk_link')
    # ### end Alembic commands ###
