"""empty message

Revision ID: 98c2ee6e7b47
Revises: 546b234e241b
Create Date: 2020-04-21 12:26:37.123479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c2ee6e7b47'
down_revision = '546b234e241b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True, comment='имя пользователя'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
