"""empty message

Revision ID: a8c0559bccef
Revises: 
Create Date: 2020-04-13 23:23:55.124191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8c0559bccef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='ID роли'),
    sa.Column('name', sa.String(), nullable=False, comment='Название роли'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='ID пользователя'),
    sa.Column('login', sa.String(), nullable=False, comment='Логин пользователя'),
    sa.Column('password', sa.LargeBinary(), nullable=False, comment='Пароль пользователя'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('mstet', sa.String(), nullable=False),
    sa.Column('ltc', sa.String(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.Column('project_price_predict', sa.Numeric(precision=11, scale=4, asdecimal=False), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('google_doc_link', sa.String(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=True, comment='ID пользователя'),
    sa.Column('activate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('points',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('mstet', sa.String(), nullable=False),
    sa.Column('ltc', sa.String(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.Column('project_price_predict', sa.Numeric(precision=11, scale=4, asdecimal=False), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('failure', sa.Boolean(), nullable=False),
    sa.Column('date_failure', sa.DateTime(), nullable=True),
    sa.Column('application_source', sa.String(), nullable=True),
    sa.Column('hermes_number', sa.Integer(), nullable=True),
    sa.Column('hermes_deadline', sa.DateTime(), nullable=True),
    sa.Column('hermes_smr_successful', sa.Boolean(), nullable=True),
    sa.Column('brigadier', sa.String(), nullable=True),
    sa.Column('project_engineer', sa.String(), nullable=True),
    sa.Column('smr', sa.Boolean(), nullable=True),
    sa.Column('svarka', sa.Boolean(), nullable=True),
    sa.Column('subcontracting_price', sa.Numeric(precision=11, scale=4, asdecimal=False), nullable=True),
    sa.Column('material_price', sa.Numeric(precision=11, scale=4, asdecimal=False), nullable=True),
    sa.Column('ks11_signed_by_ltc', sa.Boolean(), nullable=True),
    sa.Column('project_price_ks2', sa.Numeric(precision=11, scale=4, asdecimal=False), nullable=True),
    sa.Column('date_ks2', sa.DateTime(), nullable=True),
    sa.Column('google_doc_link', sa.String(), nullable=True),
    sa.Column('id_dot', sa.String(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=True, comment='ID пользователя'),
    sa.Column('status', postgresql.ENUM('IN_WORK', 'COMPLETED', 'INCOMPLETE', name='status_point'), nullable=False, comment='Тип точки'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_status'), 'points', ['status'], unique=False)
    op.create_index(op.f('ix_points_user_id'), 'points', ['user_id'], unique=False)
    op.create_table('order_users',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='ID'),
    sa.Column('auction_price', sa.Float(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=True, comment='ID пользователя'),
    sa.Column('order_id', postgresql.UUID(), nullable=True, comment='ID заказа'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_users_order_id'), 'order_users', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_users_user_id'), 'order_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_users_user_id'), table_name='order_users')
    op.drop_index(op.f('ix_order_users_order_id'), table_name='order_users')
    op.drop_table('order_users')
    op.drop_index(op.f('ix_points_user_id'), table_name='points')
    op.drop_index(op.f('ix_points_status'), table_name='points')
    op.drop_table('points')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
