"""empty message

Revision ID: b5ef51e289cd
Revises: 2e08f61a0480
Create Date: 2020-05-20 23:37:10.324349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ef51e289cd'
down_revision = '2e08f61a0480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True, comment='почта пользователя'))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True, comment='телефон пользователя'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
